[build]
builder = "nixpacks"

[build.nixpacks]
providers = ["nodejs-pnpm", "nodejs-yarn", "nodejs-npm"]

[deploy]
startCommand = "node server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
